name: create-release

on:
    push:
        branches:
            - 'main'
jobs:
    build:
        name: create-develop-release
        runs-on: ubuntu-latest

        steps:
            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.5.1
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
                
            - name: Setup Git Client
              run: |
                ssh-keyscan -H github.com >> ~/.ssh/known_hosts
                git config --global user.email "admin@digitson.com.tr"
                git config --global user.name "digitsontr"

            - name: Checkout
              uses: actions/checkout@v4
              
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3.0.3
              with:
                dotnet-version: 7.0.312
                # Authenticates packages to push to GPR
                source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
              env:
                NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'

            - name: Install dependencies
              run: dotnet restore
              env:
                NUGET_AUTH_TOKEN: ${{ github.token }}
                  
            - name: Build
              run: dotnet publish --configuration Release
                
            - name: Test
              run: dotnet test --no-restore --verbosity normal

            # Clone this repository (deploy branch) inside the "deploy" folder
            # Before clearing out, move .git folder out of the "deploy" folder
            # Recreate deploy folder, empty
            # Move .git folder back again
            # Move publish to deploy folder
            # Push files to the "deploy" branch
            - name: Deploy
              run: |
                git clone --depth 1 --single-branch -b deploy-main git@github.com:${{ github.repository }}.git deploy-main
                mv deploy-main/.git deploy-main.git
                rm -rf deploy-main
                mkdir deploy-main
                mv deploy-main.git deploy-main/.git
                cd deploy-main
                cp -R ../RoomieRosterWeb/bin/Release/net7.0/publish .
                git add .
                git diff --staged --quiet || git commit -m "Update Artifacts"
                git push
